export const FETCH_CHECKIN_DATA = 'FETCH_CHECKIN_DATA';
export const FETCH_CHECKIN_DATA_SUCCESS = 'FETCH_CHECKIN_DATA_SUCCESS';
export const FETCH_CHECKIN_DATA_FAILED = 'FETCH_CHECKIN_DATA_FAILED';
export const DELETE_CHECKIN_DATA = 'DELETE_CHECKIN_DATA';
export const DELETE_CHECKIN_DATA_SUCCESS = 'DELETE_CHECKIN_DATA_SUCCESS';
export const DELETE_CHECKIN_DATA_FAILED = 'DELETE_CHECKIN_DATA_FAILED';
export const ADD_REALTIME_EVENT = 'ADD_REALTIME_EVENT';
