export const FETCH_DASHBOARD_INFO = 'FETCH_DASHBOARD_INFO';
export const FETCH_DASHBOARD_INFO_SUCCESS = 'FETCH_DASHBOARD_INFO_SUCCESS';
export const FETCH_DASHBOARD_INFO_FAILED = 'FETCH_DASHBOARD_INFO_FAILED';
export const UPDATE_DASHBOARD_INPUT = 'UPDATE_DASHBOARD_INPUT';
export const UPDATE_DASHBOARD_INPUT_SUCCESS = 'UPDATE_DASHBOARD_INPUT_SUCCESS';
export const UPDATE_DASHBOARD_INPUT_FAILED = 'UPDATE_DASHBOARD_INPUT_FAILED';
